/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package greeter

import org.junit.Assert.assertNotNull
import kotlin.test.Test
import kotlin.test.assertTrue

class GreeterTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Greeter()
        assertNotNull(classUnderTest.getGreeting(), "getGreeting should return not null")
    }
}
