name: build master

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch HEAD^
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.

    - name: Download monodiff command
      run: curl -L https://github.com/orangain/monodiff/releases/download/v0.0.1/monodiff_linux_x86_64.tar.gz | tar zx -C ./ monodiff  # Extract `monodiff` command from tar archive and put it into current directory

    - name: Detect changed parts
      run: git diff --name-only HEAD^ | ./monodiff --prefix ":" --separator ":" --suffix :build > GRADLE_ARGS.txt && cat GRADLE_ARGS.txt

    - name: Run gradle build only for changed parts
      run: ./gradlew $(cat GRADLE_ARGS.txt)
