name: build master

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch HEAD^
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
    - uses: orangain/setup-monodiff-action@v1

    # It is advisable to use `set -eo pipefail` and to write results into files to make the job failed on error.
    - name: Detect changed parts
      run: |
        set -eo pipefail
        git diff --name-only HEAD^ | monodiff --prefix ":" --separator ":" --suffix :build > GRADLE_ARGS.txt && cat GRADLE_ARGS.txt

    - name: Run gradle build only for changed parts
      run: ./gradlew $(cat GRADLE_ARGS.txt)

    - uses: actions/upload-artifact@v2
      with:
        path: apps/*/build/libs/*.jar
